spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: cfo
    password: cfo
    url: jdbc:h2:mem:dio_kotlin_project
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html